### ISSUE TITLE
'NoneType' object is not callable

### ISSUE THREAD

**Issue by rcjiaobai** [cobrateam/splinter#1119]
use the demo code:
from splinter import Browser
browser = Browser('chrome')
browser.visit('http://google.com')

The interpreter shows:
Traceback (most recent call last):
  File "C:\Users\81406\PycharmProjects\py2023\main.py", line 2, in <module>
    browser = Browser('chrome')
  File "C:\Users\81406\AppData\Local\Programs\Python\Python39\lib\site-packages\splinter\browser.py", line 121, in Browser
    return get_driver(driver, retry_count=retry_count, *args, **kwargs)
  File "C:\Users\81406\AppData\Local\Programs\Python\Python39\lib\site-packages\splinter\browser.py", line 92, in get_driver
    return driver(*args, **kwargs)
TypeError: 'NoneType' object is not callable

couldn't figure why......

**Comment by lgeo3** [comment]
a simple `pip install selenium` fixed the issue on my side

**Comment by rcjiaobai** [comment]
> really works, thanks
