### ISSUE TITLE
ValueError using zope.testbrowser

### ISSUE THREAD

**Issue by oinopion** [cobrateam/splinter#125]
I'm trying to use zope.testbrowser, but I keep getting this error:

```
Traceback (most recent call last):
  File "/home/oinopion/.virtualenvs/meetupon/lib/python2.6/site-packages/lettuce/core.py", line 117, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/home/oinopion/Work/meetupon/meetupon/accounts/features/user-steps.py", line 24, in i_press
    button = world.browser.find_by_value(button_value).first
  File "/home/oinopion/.virtualenvs/meetupon/lib/python2.6/site-packages/splinter/driver/zopetestbrowser.py", line 116, in find_by_value
    return self.find_by_xpath('//*[@value="%s"]' % value, original_find="value", original_selector=value)
  File "/home/oinopion/.virtualenvs/meetupon/lib/python2.6/site-packages/splinter/driver/zopetestbrowser.py", line 103, in find_by_xpath
    return self.find_by_name(xpath_element.name)
  File "/home/oinopion/.virtualenvs/meetupon/lib/python2.6/site-packages/splinter/driver/zopetestbrowser.py", line 127, in find_by_name
    control = self._browser.getControl(name=name, index=index)
  File "/home/oinopion/.virtualenvs/meetupon/lib/python2.6/site-packages/zope/testbrowser/browser.py", line 383, in getControl
    label, name, self.mech_browser.forms(), include_subcontrols=True)
  File "/home/oinopion/.virtualenvs/meetupon/lib/python2.6/site-packages/zope/testbrowser/browser.py", line 389, in _get_all_controls
    onlyOne([label, name], '"label" and "name"')
  File "/home/oinopion/.virtualenvs/meetupon/lib/python2.6/site-packages/zope/testbrowser/browser.py", line 85, in onlyOne
    "Supply one and only one of %s as arguments" % description)
ValueError: Supply one and only one of "label" and "name" as arguments
```

It is caused by this line:

```
world.browser.find_by_value(button_value).first
```

It works correctly with firefox driver.

**Comment by konstantinkobs** [comment]
This still doesn't work. I call `browser.find_by_id('logIn_btn')` and get the same error message as @oinopion. It seems like if zope.testbrowser thinks that special characters are spaces...

**Comment by matclab** [comment]
`find_by_value` calls find_by_xpath which itself does:
```
    for xpath_element in html.xpath(xpath):
             if self._element_is_link(xpath_element):
                 return self._find_links_by_xpath(xpath)
             elif self._element_is_control(xpath_element):
                 return self.find_by_name(xpath_element.name)
             else:
                 elements.append(xpath_element
```
Thus it calls find_by_name on an element which has no name !
