### ISSUE TITLE
OSError on Browser()

### ISSUE THREAD

**Issue by abhillman** [cobrateam/splinter#177]
Hi all,

Thanks for your time. I'm getting an error when trying to use splinter for the first time. Here's my stack trace.

>>> from splinter.browser import Browser 
>>> browser = Browser()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/splinter/browser.py", line 44, in Browser
    return driver(_args, *_kwargs)
  File "/Library/Python/2.7/site-packages/splinter/driver/webdriver/firefox.py", line 37, in **init**
    self.driver = Firefox(firefox_profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 59, in **init**
    self.binary, timeout),
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 47, in **init**
    self.binary.launch_browser(self.profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 43, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 65, in _start_from_profile_path
    env=self._firefox_env).communicate()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 672, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1202, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Thanks again.

**Comment by colwem** [comment]
You should at the very least mention that firefox is required in the documentation.  The fact that there's a page about the chrome driver actually makes it worse.  I saw that and my first reaction was "hmm.. they mention chrome but not firefox so I guess it's not needed.  Maybe they just automatically install the part of firefox that they need in order to make this work."  If you hadn't mentioned chrome my first thought would have been "well I guess I need firefox."

**Comment by andrewsmedina** [comment]
@colwem you are right. Can you create an issue about it, to fix splinter documentation?
