### ISSUE TITLE
AttributeError: 'TemplateResponse' object has no attribute 'charset'

### ISSUE THREAD

**Issue by paveltyavin** [cobrateam/splinter#383]
Django==1.7.6
splinter==0.7.2
lxml==3.4.2

```
# coding=utf-8
from django.test import LiveServerTestCase
from django.contrib.auth import get_user_model

User = get_user_model()

from splinter import Browser


class AdminTestCase(LiveServerTestCase):
    def setUp(self):
        User.objects.create_superuser(
            username='admin',
            password='admin',
            email='admin@example.com'
        )
        self.splinter = Browser('django')
        super(AdminTestCase, self).setUp()

    def test_create_user_splinter(self):
        count_1 = User.objects.all().count()
        self.splinter.visit('%s%s' % (self.live_server_url, "/admin/"))

        self.splinter.find_by_css("#id_username").fill("admin")
        self.splinter.find_by_css("#id_password").fill("admin")

        button = self.splinter.find_by_css('[type="submit"]')
        self.assertNotEqual(button, None)

        button.click()
        self.splinter.visit('%s%s' % (self.live_server_url, "/admin/app/user/add/"))

        self.splinter.find_by_css("#id_username").fill("test")
        self.splinter.find_by_css("#id_password1").fill("test")
        self.splinter.find_by_css("#id_password2").fill("test")

        self.splinter.find_by_css("#user_form [type=submit]").first.click()
        count_2 = User.objects.all().count()

        self.assertEqual(count_1, count_2 - 1)
```

```
Traceback (most recent call last):
  File "src/app/tests/test_splinter.py", line 23, in test_create_user_splinter
    self.splinter.find_by_css("#id_username").fill("admin")
  File "env/lib/python2.7/site-packages/splinter/driver/djangoclient.py", line 174, in find_by_css
    return self.find_by_xpath(xpath, original_find="css", original_selector=selector)
  File "env/lib/python2.7/site-packages/splinter/driver/djangoclient.py", line 177, in find_by_xpath
    html = self.htmltree
  File "env/lib/python2.7/site-packages/splinter/driver/djangoclient.py", line 144, in htmltree
    self._html = lxml.html.fromstring(self.html)
  File "env/lib/python2.7/site-packages/splinter/driver/djangoclient.py", line 154, in html
    return self._response.content.decode(self._response.charset)
AttributeError: 'TemplateResponse' object has no attribute 'charset'
```

**Comment by doup** [comment]
@vinograd19 did you fix this?

**Comment by doup** [comment]
Just for reference, it seems related to #380.

**Comment by vinograd19** [comment]
no, i didn't fix. It was my first time with splinter, so I thought that it is very unstable if it didn't pass the simple test

**Comment by andrewsmedina** [comment]
I can't reproduce this bug with the splinter last version
