### ISSUE TITLE
visit function can block user's action

### ISSUE THREAD

**Issue by ralph-nj** [cobrateam/splinter#439]
At first , we could have a look at the implementation of function visit.

<pre>
def visit(self, url):
        self.connect(url)
        self.ensure_success_response()
        self.driver.get(url)
</pre>

There are three steps in this function,
first try to connect
second ensure_success_response , this steps is used to check response code.
at last , call selenium api to open url

About checking response code , my opinion is sometimes strict check isn't necessary.
example , use IIS to do authentification , we need open the page to test logon , but splinter check the response code and find it's 401, so raised , it's not a good idea.
it's the code of checking response 

<pre>
if self.code in self.http_errors:
            raise HttpResponseError(self.code, self.reason)

http_errors = (400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411,
                   412, 413, 414, 415, 416, 417, 500, 501, 502, 503, 504, 505)
</pre>

So , I think ,we can add an option to choose strict check or simple check .Anyway , visit function can't block user's action,

**Comment by ralph-nj** [comment]
it's raise output
<pre>
Traceback (most recent call last):
  File "xxxx.py", line x, in <module>
    browser.visit("http://xxxx/")
  File "build\bdist.win32\egg\splinter\driver\webdriver\__init__.py", line 181, in visit
    self.ensure_success_response()
  File "build\bdist.win32\egg\splinter\request_handler\request_handler.py", line 39, in ensure_success_response
    self.status_code.is_valid_response()
  File "build\bdist.win32\egg\splinter\request_handler\status_code.py", line 53, in is_valid_response
    raise HttpResponseError(self.code, self.reason)
HttpResponseError: 401 - Unauthorized
</pre>
