### ISSUE TITLE
add cookies to phantomjs browser have a error

### ISSUE THREAD

**Issue by galaxy6** [cobrateam/splinter#478]
phantomjs version: phantomjs-2.1.1-linux-x86_64.tar.bz2 have e error
but  phantomjs-1.9.8-linux-x86_64.tar.bz2 is normal.

code:
`from splinter import Browser

cookie = {'test':'1234'}
current_url = 'http://www.google.com'
browser = Browser('phantomjs')
browser.visit(current_url)
browser.cookies.add(cookie)  
source = browser.html
browser.quit()

`
except output:

Traceback (most recent call last):
  File "dy.py", line 37, in <module>
    dy.dynamic_request()
  File "dy.py", line 31, in dynamic_request
    browser.cookies.add(cookie)  
  File "/usr/local/lib/python2.7/dist-packages/splinter-0.7.3-py2.7.egg/splinter/driver/webdriver/cookie_manager.py", line 28, in add
    self.driver.add_cookie({'name': key, 'value': value})
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 666, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 233, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.0-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: {"errorMessage":"Can only set Cookies for the current domain","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"98","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:55891","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\"sessionId\": \"7b996980-de36-11e5-8735-cd0a007cdec8\", \"cookie\": {\"name\": \"test\", \"value\": \"1234\"}}","url":"/cookie","urlParsed":{"anchor":"","query":"","file":"cookie","directory":"/","path":"/cookie","relative":"/cookie","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/cookie","queryKey":{},"chunks":["cookie"]},"urlOriginal":"/session/7b996980-de36-11e5-8735-cd0a007cdec8/cookie"}}
Screenshot: available via screen

**Comment by engMaher** [comment]
specifying the domain for each cookie did the trick for me
get the current domain for google.com , ie:  .google.com.eg 
 cookie={
		'domain': '.google.com.eg', 
		'name':'test',
		'value':'1234',
		'path': '/',
		'expires': None
	    }
