### ISSUE TITLE
In Sample Program - Instantiation of Browser class should also include the browser name parameter

### ISSUE THREAD

**Issue by Lohit9** [cobrateam/splinter#487]
***What is the Issue ?***

In https://splinter.readthedocs.io/en/latest/tutorial.html. When creating an browser instance we need to pass it a parameter, i.e the name of the browser. But the ReadMe doesn't state anything about it. We have this issue when the issue when the use has more than one browser installed.

***The Error that we see if no parameter is passed during Browser instantiation is:***

```
Traceback (most recent call last):
  File "./sample.py", line 6, in <module>
    browser = Browser()
  File "/usr/local/lib/python2.7/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/splinter/driver/webdriver/firefox.py", line 39, in __init__
    self.driver = Firefox(firefox_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 81, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    ......
```
***How to resolve this:***

It would be better to clearly state in the line no. 3 of the sample program ( https://splinter.readthedocs.io/en/latest/tutorial.html ) that the user might need to pass the name of the browser as a parameter, something like this:

`browser = Browser('chrome')`  or 
`browser = Browser() # you might need to pass parameter(i.e your browser name) during Browser instance creation Browser('name of browser') `

I am reporting this because I recently started using the Splinter API and I found it hard to figure out why the sample program code was not running. 

Hope this helps someone else as well 😄 
Thank you!

**Comment by bmcculley** [comment]
Hi @Lohit9, thank you for reporting this issue. Do you have firefox installed on your system?

The documentation definitely needs to be updated and possibly the behavior of splinter itself. By default if [no browser argument is passed](http://splinter.readthedocs.io/en/latest/api/driver-and-element-api.html#module-splinter.browser) it automatically tries to use firefox, but if it's not there it breaks (this should be fixed to accommodate users without firefox).

**Comment by Lohit9** [comment]
Hi @bmcculley, thanks for the quick response! Yeah I don't have firefox installed and hence it broke and gave me that error. However mentioning the preferred browser as a parameter during initialization solves this error.

Also if possible a more descriptive error message may be better since this probably is a common error people face when they get started :)

**Comment by bmcculley** [comment]
@Lohit9 thank you for replying back. I'll definitely start working on getting the documentation updated and looking into the best way to fix the issue of no browser argument being passed. The error message would definitely be the easiest and probably the most efficient though :)

**Comment by Lohit9** [comment]
@bmcculley Thanks 😄
