### ISSUE TITLE
Flask Driver Not Found

### ISSUE THREAD

**Issue by FlamingFeesh** [cobrateam/splinter#490]
New to flask and programming in general. This is what my code looks like in my app:

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import splinter

app = Flask(__name__)
app.secret_key = 'my_secret_key'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///./meal_data.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
db = SQLAlchemy(app)
browser = splinter.Browser('flask', app=app)
```

This error comes up:

```
Traceback (most recent call last):
  File "/Users/19tp01/flask-programs/lunchbot/venv/lib/python3.4/site-packages/splinter/browser.py", line 60, in Browser
    driver = _DRIVERS[driver_name]
KeyError: 'flask'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "/Users/19tp01/flask-programs/lunchbot/app/__init__.py", line 10, in <module>
    browser = splinter.Browser('flask', app=app)
  File "/Users/19tp01/flask-programs/lunchbot/venv/lib/python3.4/site-packages/splinter/browser.py", line 62, in Browser
    raise DriverNotFoundError("No driver for %s" % driver_name)
splinter.exceptions.DriverNotFoundError: No driver for flask
```

I'm pretty sure I'm following the documentation correctly, and the actual app works fine. All my dependencies have been installed, so I don't know what's the issue here.

Thanks

**Comment by andrewsmedina** [comment]
what version of splinter are you using?

**Comment by FlamingFeesh** [comment]
0.7.3

**Comment by andrewsmedina** [comment]
looks like that flask is not installed

**Comment by FlamingFeesh** [comment]
I'm pretty sure it's installed. The actual flask app is running smoothly.

**Comment by norm** [comment]
I think you have some dependencies (either or both of `lxml` and `cssselect`) missing. You can install them with `pip install splinter[flask]` — which installs splinter and all dependencies required for the `flask` browser. This is mentioned in the docs http://splinter.readthedocs.io/en/latest/drivers/flask.html but it is a subtle point (looks a lot like `pip install splinter flask`) and is easily missed.

**Comment by FlamingFeesh** [comment]
I remember I did install using `pip install splinter[flask]` but to make sure I did it again. And yes, they are installed:

```
$ pip install splinter[flask]
Requirement already satisfied (use --upgrade to upgrade): splinter[flask] in ./venv/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): selenium>=2.47.1 in ./venv/lib/python3.4/site-packages (from splinter[flask])
Requirement already satisfied (use --upgrade to upgrade): cssselect; extra == "flask" in ./venv/lib/python3.4/site-packages (from splinter[flask])
Requirement already satisfied (use --upgrade to upgrade): Flask>=0.10; extra == "flask" in ./venv/lib/python3.4/site-packages (from splinter[flask])
Requirement already satisfied (use --upgrade to upgrade): lxml>=2.3.6; extra == "flask" in ./venv/lib/python3.4/site-packages (from splinter[flask])
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in ./venv/lib/python3.4/site-packages (from Flask>=0.10; extra == "flask"->splinter[flask])
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in ./venv/lib/python3.4/site-packages (from Flask>=0.10; extra == "flask"->splinter[flask])
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in ./venv/lib/python3.4/site-packages (from Flask>=0.10; extra == "flask"->splinter[flask])
Requirement already satisfied (use --upgrade to upgrade): click>=2.0 in ./venv/lib/python3.4/site-packages (from Flask>=0.10; extra == "flask"->splinter[flask])
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in ./venv/lib/python3.4/site-packages (from Jinja2>=2.4->Flask>=0.10; extra == "flask"->splinter[flask])
```

**Comment by andrewsmedina** [comment]
Can you try to import the FlaskDriver class? I believe that this is not registered because some error is happening:

```
from splinter.driver.flaskclient import FlaskClient
```

**Comment by FlamingFeesh** [comment]
Yes. That appears to have fixed it. However this error still pops up:

```
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "/Users/19tp01/flask-programs/lunchbot/app/__init__.py", line 5, in <module>
    from splinter.driver.flaskclient import FlaskClient
  File "/Users/19tp01/flask-programs/lunchbot/venv/lib/python3.4/site-packages/splinter/driver/flaskclient.py", line 13, in <module>
    import lxml.html
  File "/Users/19tp01/flask-programs/lunchbot/venv/lib/python3.4/site-packages/lxml/html/__init__.py", line 54, in <module>
    from .. import etree
ImportError: dlopen(/Users/19tp01/flask-programs/lunchbot/venv/lib/python3.4/site-packages/lxml/etree.so, 2): Library not loaded: libxml2.2.dylib
  Referenced from: /Users/19tp01/flask-programs/lunchbot/venv/lib/python3.4/site-packages/lxml/etree.so
  Reason: Incompatible library version: etree.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
```

I've searched google on how to fix this, apparently by installing libxml2. My attempts so far have not worked (I'm running in a virtualenv, so the normal brew command does not work), but I'm going to keep at it. If anyone has a solution to this, that would be greatly appreciated.

Thanks for your help

**Comment by erm3nda** [comment]
@FlamingFeesh Well, the error says that you need version 12 or later. I don't know where did you get the libxml2.2.dylib, but you cannot have both at time. So, case you're not in virtualenv and libxml2.2.dylib is a system package, u could use virtualenv to install everything you need (included versiones) of each component you require. Case of etree, u should try with `pip install etree==12`. 
Another way should try to update libxml.
