### ISSUE TITLE
ImportError: cannot import name patterns when trying to run tests

### ISSUE THREAD

**Issue by hjwp** [cobrateam/splinter#525]
Just pulled down the repo, created a fresh virtualenv, and am seeing this traceback when I try to run the tests.

tried with python 3.5 and 2.7. tried with `./run_tests.py` and `make test`.

```
======================================================================
ERROR: test_accessing_attributes_of_inputs (tests.test_djangoclient.DjangoClientDriverTest)
should allow input's attributes retrieval
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/harry/workspace/splinter/tests/test_djangoclient.py", line 36, in setUp
    self.browser.visit(EXAMPLE_APP)
  File "/home/harry/workspace/splinter/splinter/driver/lxmldriver.py", line 39, in visit
    self._do_method('get', url)
  File "/home/harry/workspace/splinter/splinter/driver/djangoclient.py", line 115, in _do_method
    self._response = func_method(url, data=data, follow=True, **extra)
  File "/home/harry/.virtualenvs/splinter/local/lib/python2.7/site-packages/django/test/client.py", line 529, in get
    **extra)
  File "/home/harry/.virtualenvs/splinter/local/lib/python2.7/site-packages/django/test/client.py", line 333, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/harry/.virtualenvs/splinter/local/lib/python2.7/site-packages/django/test/client.py", line 409, in generic
    return self.request(**r)
  File "/home/harry/.virtualenvs/splinter/local/lib/python2.7/site-packages/django/test/client.py", line 494, in request
    six.reraise(*exc_info)
  File "/home/harry/.virtualenvs/splinter/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/harry/.virtualenvs/splinter/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/harry/.virtualenvs/splinter/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/harry/.virtualenvs/splinter/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 270, in resolve
    for pattern in self.url_patterns:
  File "/home/harry/.virtualenvs/splinter/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/harry/.virtualenvs/splinter/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/harry/.virtualenvs/splinter/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/harry/.virtualenvs/splinter/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "tests/fake_django/urls.py", line 1, in <module>
    from django.conf.urls import patterns, include, url
ImportError: cannot import name patterns
```

**Comment by hjwp** [comment]
(full test run currently ends with:

```
Ran 907 tests in 326.354s

FAILED (failures=1, errors=163)
```
)

**Comment by rahul6612** [comment]
try this

> from django.conf.urls import *
