### ISSUE TITLE
element is visiable but can 't fill content

### ISSUE THREAD

**Issue by windanchaos** [cobrateam/splinter#534]
`from splinter import Browser
import time
import sys
import random
account = ""
passport = ""
backgroundURL = "http://shop.aiyaohong.com"
productName = '回归测试商品'
shortDes = '回归测试商品.....'
productCode = '11211123'

browser = Browser('chrome')
browser.visit(backgroundURL)
browser.fill('account', account)
browser.fill('password', passport)
browser.find_by_value('登    录').click()

browser.find_by_text('商品管理').click()
browser.find_by_text('商品仓库').click()
browser.find_by_text('发布商品').click()
browser.find_by_id('item_2').click()
browser.find_by_text('下一步').click()

browser.find_by_id('productName').fill(productName)
browser.find_by_id('shortDes').fill(shortDes)
browser.find_by_id('productCode').fill(productCode)
browser.find_by_text('添加规格项目').click()
browser.find_by_text('添加规格').click()
browser.find_by_xpath('//*[@id="addSkuWindow"]/div/div/fieldset[1]/div/div/span/span/input').fill('净含量')
browser.find_by_xpath('//*[@id="toAddSku"]').click()

time.sleep(2)
browser.find_by_xpath('//*[@id="addSpecV_0"]').click()
time.sleep(1)
browser.find_by_xpath('//*[@id="skuValueWindow"]/div/div/fieldset/div/div[1]/span/span/input').fill('1L')
browser.find_by_xpath('//*[@id="skuValueWindow"]/div/div/fieldset/div/div[2]/button').click()
time.sleep(2)
browser.find_by_xpath('//*[@id="addSpecV_0"]/a').click()
time.sleep(1)
browser.find_by_xpath('//*[@id="skuValueWindow"]/div/div/fieldset/div/div[1]/span/span/input').fill('2L')
browser.find_by_xpath('//*[@id="skuValueWindow"]/div/div/fieldset/div/div[2]/button').click()
inputElement = browser.find_by_xpath('//*[@id="skuShow"]/div[1]/div/div[2]/div[1]/span[2]/span/input[1]')
if (inputElement.visible):
    print(inputElement)
    print(inputElement.visible)
    inputElement.fill(12)`

Log:
`[<splinter.driver.webdriver.WebDriverElement object at 0x042A9730>]
True
Traceback (most recent call last):
  File "D:/Code/GitHub/mk-Regression-testing/sign_in.py", line 49, in <module>
    inputElement.fill(12)
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\splinter-0.7.5-py3.5.egg\splinter\driver\webdriver\__init__.py", line 529, in fill
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\splinter-0.7.5-py3.5.egg\splinter\driver\webdriver\__init__.py", line 512, in _set_value
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\selenium-3.0.2-py3.5.egg\selenium\webdriver\remote\webelement.py", line 347, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': keys_to_typing(value)})
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\selenium-3.0.2-py3.5.egg\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\selenium-3.0.2-py3.5.egg\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\selenium-3.0.2-py3.5.egg\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 10.0.14393 x86_64)
`

inputElement visible is True but can't fill 
who can help?

**Comment by windanchaos** [comment]
with selenium ,I can fill the content :
```
browser.find_by_id('batch_quto').clear()
browser.find_by_id('batch_quto').fill("120")
browser.find_by_xpath("(//input[@type='text'])[6]").click()
```

I followed the same way with splinter:
```
browser.find_by_id('batch_quto').clear()
browser.find_by_id('batch_quto').fill("120")
browser.find_by_xpath("(//input[@type='text'])[6]").click()
```

the log is 

> selenium.common.exceptions.InvalidElementStateException: Message: invalid element state: Element is not currently interactable and may not be manipulated

that's means the splinter should not alert exception when the input element exist but not visible .
