### ISSUE TITLE
Headless Chrome Not Working

### ISSUE THREAD

**Issue by djstein** [cobrateam/splinter#552]
On Splinter 0.7.5 following exactly what is in the documentation: http://splinter.readthedocs.io/en/latest/drivers/chrome.html?highlight=headless#using-headless-option-for-chrome

```
>>> from splinter import Browser
>>> browser = Browser('chrome', headless=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/splinter/driver/webdriver/chrome.py", line 28, in __init__
    self.driver = Chrome(chrome_options=options, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'headless'
```

**Comment by miohtama** [comment]
The documentation applies to the master branch version of Splinter.

To install Splinter directly from github:

       pip install -e "git+git@github.com:cobrateam/splinter.git@21f714f377e161cc7321de1edbfaebd5cca28b3b#egg=splinter"

**Comment by andrewsmedina** [comment]
this feature was released in 0.7.6.

**Comment by miohtama** [comment]
Where are the latest releases and changelog kept?

Latest PyPi is 0.7.5 https://pypi.python.org/pypi/splinter/

Laatest Github is 0.7.4 https://github.com/cobrateam/splinter/releases

**Comment by andrewsmedina** [comment]
you can see the changelog in https://splinter.readthedocs.io/en/latest/news/0.7.6.html
