### ISSUE TITLE
Can't use splinter

### ISSUE THREAD

**Issue by Jarod00** [cobrateam/splinter#571]
Hey i tried to execute the example code from the wiki, but i get this error message. Can someone help me? I'm sorry, if that is an dumb question. I'm quite new to python

Traceback (most recent call last):
  File "dbconnect.py", line 3, in <module>
    browser = Browser()
  File "C:\Python27\lib\site-packages\splinter\browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "C:\Python27\lib\site-packages\splinter\driver\webdriver\firefox.py", line 57, in __init__
    timeout=timeout, **kwargs)
  File "C:\Python27\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 144, in __init__
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by andrewsmedina** [comment]
The default driver is `Firefox` thats use the `geckodriver`. You should have the `geckodriver` installed to use splinter with firefox.
