### ISSUE TITLE
HTTP Error 403: request disallowed by robots.txt

### ISSUE THREAD

**Issue by Constantin07** [cobrateam/splinter#702]
Running in python venv (MacOS) `Python 2.7.16`

Installed packages in venv:
```
splinter==0.11.0
zope.testbrowser==5.3.3
lxml==4.3.4
cssselect==1.0.3
mechanize==0.4.2
```

```python
from splinter import Browser

jenkins_url = 'some value here'

browser = Browser('zope.testbrowser')
browser.visit(jenkins_url)
```

getting back:

```
Traceback (most recent call last):
  File "jenkins_test.py", line 9, in <module>
    browser.visit(jenkins_url)
  File "/Users/homedir/Documents/Jenkins_Test/venv/lib/python2.7/site-packages/splinter/driver/zopetestbrowser.py", line 81, in visit
    self._browser.open(url)
  File "/Users/homedir/Documents/Jenkins_Test/venv/lib/python2.7/site-packages/zope/testbrowser/browser.py", line 252, in open
    self._processRequest(url, make_request)
  File "/Users/homedir/Documents/Jenkins_Test/venv/lib/python2.7/site-packages/zope/testbrowser/browser.py", line 276, in _processRequest
    resp = make_request(reqargs)
  File "/Users/homedir/Documents/Jenkins_Test/venv/lib/python2.7/site-packages/zope/testbrowser/browser.py", line 250, in make_request
    return self.testapp.get(url, **args)
  File "/Users/homedir/Documents/Jenkins_Test/venv/lib/python2.7/site-packages/webtest/app.py", line 335, in get
    expect_errors=expect_errors)
  File "/Users/homedir/Documents/Jenkins_Test/venv/lib/python2.7/site-packages/zope/testbrowser/browser.py", line 92, in do_request
    self._assertAllowed(req.url)
  File "/Users/homedir/Documents/Jenkins_Test/venv/lib/python2.7/site-packages/zope/testbrowser/browser.py", line 89, in _assertAllowed
    raise RobotExclusionError(url, 403, msg, [], None)
zope.testbrowser.browser.RobotExclusionError: HTTP Error 403: request disallowed by robots.txt
```

What am I doing wrong ?

**Comment by mattfeury** [comment]
looks like it was removed here: https://github.com/cobrateam/splinter/commit/a7cbbf9efd6f987779eaad90f8af2d9758a42b1e

no clue why. @andrewsmedina was the author so may be able to shed some light

**Comment by andrewsmedina** [comment]
This was removed on zope.testbrowser upgrade. I believe that we should figure out how to fix it using the current version of this driver.

**Comment by mo-han** [comment]
Just tried a simple workaround, which overrides `_assertAllowed` method to by-pass checking agains `zope.testbrowser.browser._allowed`, here's the code:

```python
import splinter.driver.zopetestbrowser

def pass_assert_allowed(*args):
    return

b = splinter.browser.ZopeTestBrowser()
b._browser.testapp._assertAllowed = pass_assert_allowed
```

Now can `visit` any URL without `request disallowed` error.
But frankly `zope.testbrowser` cannot handle lots of site well, `visit` probably still failed for other reason. Personally speaking, firefox or chrome is better choice.
