### ISSUE TITLE
Main example throws error

### ISSUE THREAD

**Issue by Zylatis** [cobrateam/splinter#724]
When I run the given Google example on Linux i get the following (python3.6)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/splinter/element_list.py", line 42, in __getitem__
    return self._container[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/splinter/element_list.py", line 76, in __getattr__
    return getattr(self.first, name)
  File "/usr/local/lib/python3.6/dist-packages/splinter/element_list.py", line 57, in first
    return self[0]
  File "/usr/local/lib/python3.6/dist-packages/splinter/element_list.py", line 46, in __getitem__
    self.find_by, self.query
splinter.exceptions.ElementDoesNotExist: no elements could be found with name "btnG"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/splinter/element_list.py", line 79, in __getattr__
    return getattr(self._container, name)
AttributeError: 'list' object has no attribute 'click'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "splinter_test.py", line 6, in <module>
    browser.find_by_name('btnG').click()
  File "/usr/local/lib/python3.6/dist-packages/splinter/element_list.py", line 83, in __getattr__
    self.__class__.__name__, name
AttributeError: 'ElementList' object has no attribute 'click'

```

I did an inspect on the google website and it seems the button is called 'btnK' so I changed it to that but now get this
```
selenium.common.exceptions.ElementNotInteractableException: Message: Element <input class="gNO89b" name="btnK" type="submit"> could not be scrolled into view
```

**Comment by andrewsmedina** [comment]
@Zylatis what splinter version are you using?

**Comment by Zylatis** [comment]
Apologies for delayed reply: version is 0.11.0
