### ISSUE TITLE
splinter.exceptions.DriverNotFoundError: No driver for chrome.webdriver

### ISSUE THREAD

**Issue by abhiomkar** [cobrateam/splinter#92]
I'm getting `DriverNotFoundError` exception when creating a firefox browser instance.

I'm on Mac OS X Snow Leopard with Firefox 5.0.1 -

```
Python 2.6.1 (r261:67515, Aug  2 2010, 20:10:18) 
[GCC 4.2.1 (Apple Inc. build 5646)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from splinter.browser import Browser
browser = Browser('firefox.webdriver')
>>> browser = Browser('firefox.webdriver')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.6/site-packages/splinter/browser.py", line 37, in Browser
    raise DriverNotFoundError("No driver for %s" % driver_name)
splinter.exceptions.DriverNotFoundError: No driver for firefox.webdriver
```

am I missing something?

Thanks!

**Comment by machinavic** [comment]
What about if the web browser is Chrome? I couldn't solve this issue?
